language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
install:
- pip install -e .
script: pytest
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ltCFPDMMvWBbsS65d55vXODhxpYbXqF7Px4XT94Up2dJa6qk9qFWh/irOvd9KX3DZLG+wa+xxA55M/qyXvWup0hRxIQLXe3bSZ50migFOZ7mF0V507XDe0z3dqALY+avMN2Ni+W/Y6FXMNBlRjJwsHEglX4tWTRkU587qLZP3iNZWtmisMVH/j/8sSragm5wzj/AlsUXGSyU5EZvSHM6LwjrE+oNxXoO+D+z0mPRcrpmxZmbTQNOT4fktnAxBA/Gx5UtfHL1Xp32xCY1Pl4vcpcanv8V/6Cff40alqZ9xWNDockR52xMTGG8wduT+xpCLIYSooS+GuQ5dDbTovRGM7s2LmxbyCkcpS8h1YPFqeSe7+Xrj2ZKYGhVOZfqLpHgqndVWhHJLDCXxAAPMn2680BA8P41+dbHPipF6fpAIr69sdz92Q698tyibKwbg0D4JnU2G990UOSMlcpu7VBxypB1O4GDdDe4U7vMWyFtYpOJOfdYK3t6bbIMHwsjju9r0iQdXk7iZGHfMWCA65XikHPtBh4XkOibuw980zmFOBX8CCxqXAkdkOQzHRjxiVGUh7BLsnDm2eZTgsiHlJ8AosdXqvexVzH6/CrG70JDgFn/Uh3/MEXxiuUdJg13w/NEgA20D6xtgLUh+pYrQOyw+KedVoK0pZxHO/EV/T6FxD8=
  on:
    tags: true
