sudo: required

language: python

services:
  - docker

before_install:
- docker pull spfrnd/parts_test:latest
- docker run -d spfrnd/parts_test:latest /bin/sh -c "git pull; pytest; cd doc; ./run_apidoc.sh; make clean; make html;"

script:
- docker cp $(docker ps | grep parts_test | awk '{print $1;}'):/app/parts/doc/_build/html .

deploy:
  provider: pages
  local-dir: html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target-branch: gh-pages
  keep-history: true
  on:
    branch: master
